name: Auto Build Script

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  codacy-analysis-cli:
      name: Codacy Analysis CLI
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Run Codacy Analysis CLI
          uses: codacy/codacy-analysis-cli-action@master

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Setting up JDK"
      - name: Check commit message
        uses: gsactions/commit-message-checker@v2
        with:
            pattern: '^(feat|chore|test|refactor|fix|enhance)\([0-9]+\):.*'
            flags: 'gm'
            error: 'Your first line has to contain a commit type like "[BUGFIX]".'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check code format
        run: ./gradlew ktlintcheck
      - run: echo "Building Debug APK."
      - name: Build with Gradle
        run: ./gradlew build
      - run: echo "Build status report=${{ job.status }}."
